### ISSUE TITLE
V1.4.0.0 getting stuck on sync with error

### ISSUE THREAD

**Issue by foomip** [decenomy/SAPP#21]
Re-Submitting this issue as it is not resolved

Once syncing a node from scratch reaches block 900013, it stops syncing and these errors start appearing in the logs.

ERROR: AcceptBlock : prev block f086800cba79e1b725677d40cdce4795578fd0e09ee9f5e49ab8ca3ab287056c is invalid, unable to add block 9297b177a4741dde9266f19877d298f01e3ebe15e39128eb29ae74e27232c3d0
ERROR: ProcessNewBlock : AcceptBlock FAILE
Machine specs:

    OS: Ubuntu 18.04.4
    CPU: Ryzen 7 3700X
    RAM: 64GB
    Disk size: 1TB
    Disk Type (HD/SDD): HD (Raid 1)

I tried using the bootstrap, but it ends up showing the same error.

Some more details

Appied the latest bootstrap (10 Jan 2021), masternodes and wallet are now getting stuck of block 901877 with the same error.

**Comment by trilite** [comment]
Hi,
I am having several issues:
1. My local wallet didn't sync. Probably that is solved using the importwallet option 
2. My Maternodes won't sync. I get block fails for each masternode (same as OP)

**Comment by bedri** [comment]
Bootstrap at http://sappexplorer.com/bootstrap.zip is updated twice after creation of this issue. Applying the updated bootstrap fixes the chain stall issue in my tests.
Can you please use the updated bootstrap and feedback the result here? @trilite @foomip

**Comment by bedri** [comment]
No response for a long time. I guess this issue is solved with 1.4.1 version. Closing it.
