### ISSUE TITLE
Install / run SAPP wallet for Linux

### ISSUE THREAD

**Issue by vitiumartis** [decenomy/SAPP#30]
Need help.
How can I install / run the SAPP wallet for Linux? The ZIP file contain 4 files. (sapphire-cli, sapphired, sapphire-qt, sapphire-tx).
Where can I find any tutorial? 

For Windows its easy contain a setup file.

Thanks.

**Comment by crypt0p3t3r** [comment]
our documentation is on https://docs.decenomy.net/
